name: Run Bilingual Data Crawler for Nôm Script and Vietnamese Script

on:
  schedule:
    - cron: "0 8 * * *"
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
        
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
        
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # pytest: Lệnh này thực hiện việc chạy các bài kiểm tra bằng pytest. 
    # Các bài kiểm tra được định nghĩa trong các tệp mã nguồn Python 
    # với tên bắt đầu bằng test_ hoặc kết thúc bằng _test 
    # hoặc trong các thư mục có tên test hoặc tests. pytest sẽ tự động tìm 
    # và thực hiện các bài kiểm tra trong mã nguồn của bạn.
    # - name: Test with pytest
    #   run: |
    #     conda install pytest
    #     pytest

    - name: Install Jupyter
      run: |
        python -m pip install --upgrade pip
        pip install jupyter

    - name: Run NLP_Project notebooks
      run: |
        for file in $(find . -name 'NLP_Project*.ipynb'); do
          jupyter nbconvert --execute "$file" --to python
        done

    - name: Run Evaluation scripts
      run: |
        for file in $(find . -name 'SourceCode_EveluationResult.py'); do
          python "$file"
        done
